spring:
  application:
    name: enoca-ecommerce

# database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/enoca-ecommerce
    username: postgres
    password: admin

# Jpa configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# sql configuration
  sql:
    init:
      mode: always

# secure configuration
  security:
    oauth2:
      resourceserver:
        # with jwt token
        jwt:
          issuer-uri: https://kc.yukseluyghur.com/realms/enoca-dev


# swagger-ui configuration
springdoc:
  swagger-ui:
    path: /show-swagger
    oauth:
      client-id: enoca-ecommerce
      client-secret: M7EJ85BxG91vwIUxVDgXOR2JjYHuTqxY

# keycloak properties
keycloak:
  realm_name: enoca-dev
  server-url: https://kc.yukseluyghur.com
  client-id: admin-cli
  grant-type: password
  username: admin
  password: Enoca123
  application_clientId: enoca-ecommerce

