spring:
  application:
    name: enoca-ecommerce

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/enoca-ecommerce
    username: postgres
    password: admin

# secure with authentication
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://kc.yukseluyghur.com/realms/cydeo-dev


#springdoc:
#  swagger-ui:
#    oauth:
#      client-id: ticketing-app
#      client-secret: HbjtXoW0IMAgq91lkD5cRmRIDNz10CHl

