spring:
  application:
    name: enoca-ecommerce

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/enoca-ecommerce
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always




springdoc:
  swagger-ui:
    path: /show-swagger
